// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1:string):Promise<string>;

export function CheckLicense():Promise<boolean>;

export function GetMachineID():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportPurchaseVoucher(arg1:string):Promise<string>;

export function SaveLogToDailyFile(arg1:string,arg2:number,arg3:number,arg4:number,arg5:Array<string>):Promise<void>;

export function SelectExcelFile():Promise<string>;
