// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function GetMachineID() {
  return window['go']['main']['App']['GetMachineID']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportPurchaseVoucher(arg1) {
  return window['go']['main']['App']['ImportPurchaseVoucher'](arg1);
}

export function ImportSalesVoucher(arg1) {
  return window['go']['main']['App']['ImportSalesVoucher'](arg1);
}

export function SaveLogToDailyFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveLogToDailyFile'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectExcelFile() {
  return window['go']['main']['App']['SelectExcelFile']();
}
